=== shir18/autobid/docs/experiment-09/q2_dealership.dtd
<!ELEMENT dealership (car+)>
<!ELEMENT car (model, brand+, year, price?)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== shir18/autobid/docs/experiment-09/q2_dealership.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dealership SYSTEM "q2_dealership.dtd">
<dealership>
  <car>
    <model>City</model>
    <brand>Honda</brand>
    <year>2022</year>
    <price>1150000</price>
  </car>
  <car>
    <model>Swift</model>
    <brand>Maruti Suzuki</brand>
    <year>2023</year>
    <!-- Price is optional for upcoming/unlisted cars -->
  </car>
</dealership>
